### ISSUE TITLE
Add custom 3d part models

### ISSUE THREAD

**Issue by mike4192** [mike4192/spotMicro#3]
I modified some of KDY's parts to improve joint stability for the shoulder joint (in the original model, it is supported only on one side of it's axis). This issue is to add my custom parts (or links to them on thingverse) and some description of how to print them, and additional hardware required.

**Comment by Hardy5012** [comment]
Does cls6336hv files have solved this issue (in the original model, it is supported only on one side of it's axis)

**Comment by rafaturtle** [comment]
Wondering if you can also share the plate with the screw placements for the Rpi. thanks heaps!

**Comment by mike4192** [comment]
Just merged in a updated readme that has thingverse links to my custom shoulder assembly parts, as well as RPi and servo board platforms I created.
