### ISSUE TITLE
PS4 Controller

### ISSUE THREAD

**Issue by sffranke** [mike4192/spotMicro#6]
Hello again, t see that he code mentions a PS4 Controller, can you please give a hint how to use it?

**Comment by mike4192** [comment]
Hi,

Unfortunately my project does not support a PS4 controller. The remnants of code you see referencing a PS4 controller is likely from code I used as inspiration from the stanford robotics club. Please see the link at the bottom of the main readme file for a link to their source code.

Unfortunately I can't provide much info on how to use a PS4 controller. I would suggest finding code that gets input from the PS4 controller and which would update the values in the command class.

**Comment by sffranke** [comment]
Hi Mike,

thank you for pointing the right direction!
