### ISSUE TITLE
Using Different Servos

### ISSUE THREAD

**Issue by GetLifty** [mike4192/spotMicro#69]
I understand that the servos listed are perfect but they are very expensive, can I use any other servos such as CLS6336HV. I understand that you cant use the MG996R because they arent arent strong enough, but are there any other servos in a close price range that will work? Im thinking around $7 per servos rather than the $13 that the listed ones are (converted from GBP).

**Comment by mike4192** [comment]
I am not aware of other comparable servos that will work, sorry. Making a 12 DOF legged robot is not a trivial mechanical problem and requires robust servos.
You will need to do your own research for alternatives. I suggest looking and asking on existing spot micro discord channels for advice.
