### ISSUE TITLE
Can't download the spot_micro_motion_cmd/libs directory

### ISSUE THREAD

**Issue by fjblau** [mike4192/spotMicro#9]
Not sure what is going on but it doesn't copy with the clone and when I try and sync dependencies I get a permissions error

**Comment by kejincan0527** [comment]
When you download Mike's code for the first time, come to Mike‘s project folder
```
git clone --recurse-submodules https://github.com/mike4192/spotMicro.git
$cd spotMicro
```
modify .gitmodules
```
vim .gitmodules
```
chang url `ssh` to `https`
git@github.com:mike4192/xxx.git
to 
https://github.com/mike4192/xxx.git

and run
```
git submodule sync
git submodule init
git submodule update
```
You will get the complete project.

**Comment by mike4192** [comment]
Thank you for commenting on elaborated sub module checkout instructions. I plan to add these instructions explicitly to the readme soon.
